[workspace]
authors = ["Hashir <hashirbutt2610@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "GTK"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120907,<0.27"

[activation.env]
MODULAR_MOJO_MAX_SYSTEM_LIBS = "-lm,-L.pixi/envs/default/lib/,-L/opt/homebrew/Cellar/gtk4/4.20.3/lib,-lgtk-4,-L/opt/homebrew/Cellar/pango/1.57.0_1/lib,-lpangocairo-1.0,-lpango-1.0,-L/opt/homebrew/Cellar/harfbuzz/12.2.0_1/lib,-lharfbuzz,-L/opt/homebrew/lib,-lgdk_pixbuf-2.0,-L/opt/homebrew/Cellar/cairo/1.18.4/lib,-lcairo-gobject,-lcairo,-L/opt/homebrew/Cellar/graphene/1.10.8/lib,-lgraphene-1.0,-L/opt/homebrew/Cellar/glib/2.86.2/lib,-lgio-2.0,-lgobject-2.0,-lglib-2.0,-L/opt/homebrew/opt/gettext/lib,-lintl,-L/opt/homebrew/Cellar/libepoxy/1.5.10/lib,-lepoxy"